{
  "teacherId": "hv7494",
  "name": "harsha",
  "district": "Thane",
  "email": "akshaymurari184@gmail.com",
  "password": "teacher@123",
  "address": "Alwal,Ganesh Enclave\r\n97/p",
  "city": "undefined",
  "state": "Maharashtra",
  "mobile": "9898989898",
  "religion": "Hindu",
  "aadharNumer": "258898776523",
  "surname": "bammidi",
  "dob": "undefined",
  "fatherName": "madhu",
  "motherName": "prasanna krishna",
  "gender": "Male",
  "maritalStatus": "Unmarried",
  "caste": "BC-A",
  "trainingCertificate": "undefined",
  "medCertificate": "undefined",
  "mphilCertificate": "undefined",
  "DateOfIssue": "08-09-1998",
  "casteCertificateNo": "ABCD123",
  "nomineeName": "madhu",
  "relation": "father",
  "permenantId": "678954326785",
  "ownerEmail": "akshaymurari184@gmail.com",
  "ownerPassword": "akshay",
  "sscCourseTitle": "SSC ",
  "sscCourseCode": "undefined",
  "sscCourseSubject": "SSC",
  "sscBoardName": "Board of Secondary Education",
  "sscSchoolName": "Jeevan Shikshan Vidya Mandir",
  "sscMedium": "English",
  "sscFirstLanguage": "Marathi",
  "sscPassedMonthYear": "06/1991",
  "sscMarksSecured": "567",
  "sscMaximumMarks": "600",
  "sscHallTicketNo": [
    "1991000191",
    "1991000191"
  ],
  "sscPercentage": "undefined",
  "sscCertificateNo": "CDE134",
  "interCourseTitle": "Intermediate",
  "interCourseSubject": "Interediate-MPC",
  "interBoardName": "undefined",
  "interCollege": "Narayana Junior College",
  "interMedium": "English",
  "interStream": "MPC",
  "interPassedMonthYear": "06/1993",
  "interMarksSecured": "966",
  "interMaxMarks": "1000",
  "interHallTicketNo": "1993000182",
  "interCertificateNo": "JNMU156",
  "degreeCourseTitle": "B.Ed",
  "degreeCourseSubject": "Bachelor of Education-Mathematics",
  "degreeName": "Bachelor of Education",
  "degreeUniversity": "Bharati Vidyapeeth",
  "degreeMedium": "English",
  "degreeBranch": "Mathematics",
  "degreePassedMonthYear": "06/1994",
  "degreeMarksSecured": "879",
  "degreeMaximumMarks": "1000",
  "degreeHallTicketNo": "1994000187",
  "degreeCertificateNo": "YHIKW125",
  "postDegreeCourseTitle": "B.Ed",
  "postDegreeCourseSubject": "Master of Education-Mathematics",
  "postDegreeName": "Master of Education",
  "postDegreeUniversity": "Bharati Vidyapeeth",
  "postDegreeMedium": "English",
  "postDegreeBranch": "undefined",
  "postDegreePassedMonthYear": "undefined",
  "postDegreeMarksSecured": "789",
  "postDegreeMaximumMarks": "1000",
  "postDegreeHallTicketNo": "1996000187",
  "postDegreeCertificateNo": "RWFDU198",
  "trainingCourseTitle": "undefined",
  "trainingCourseSubject": "undefined",
  "trainingPassedMonthYear": "undefined",
  "trainingMarksSecured": "undefined",
  "trainingMaximumMarks": "undefined",
  "trainingHallTicketNo": "undefined",
  "trainingCertificateNo": "undefined",
  "medCourseTitle": "undefined",
  "medCourseSubject": "undefined",
  "medPassedMonthYear": "undefined",
  "medMarksSecured": "undefined",
  "medMaximumMarks": "undefined",
  "medHallTicketNo": "undefined",
  "medCertificateNo": "undefined",
  "mphilCourseTitle": "undefined",
  "mphilCourseSubject": "undefined",
  "mphilPassedMonthYear": "undefined",
  "mphilMarksSecured": "undefined",
  "mphilMaximumMarks": "undefined",
  "mphilHallTicketNo": "undefined",
  "passedDepartmentalTest": "undefined",
  "noOfTests": "undefined",
  "nameOfDepartmentalTest": "undefined",
  "regdNo": "undefined",
  "passedYear": "undefined",
  "appointingAuthority": "MEO",
  "dateOfJoining": "undefined",
  "school": "ZPHST",
  "position": "S.G.T",
  "salary": "8,50,000",
  "appointmentLetter": "8AG_KKCRn2.pdf",
  "sscCertificate": "PQFlvWvXq.pdf"
}